mod alient_types;
mod arrays;
mod cli;
mod conditionals;
mod enums;
mod functions;
mod loops;
mod pointer_ref;
mod print;
mod strings;
mod structs;
mod traits;
mod tuples;
mod types;
mod vars;
mod vectors;
mod wrap_unwrap;

fn main() {
    println!("=====PRINT=====");
    print::run();
    println!("=====VARS=====");
    vars::run();
    println!("=====TYPES=====");
    types::run();
    println!("=====STRINGS=====");
    strings::run();
    println!("=====TUPLES=====");
    tuples::run();
    println!("=====ARRAYS=====");
    arrays::run();
    println!("=====VECTORS=====");
    vectors::run();
    println!("=====CONDITIONALS=====");
    conditionals::run();
    println!("=====LOOPS=====");
    loops::run();
    println!("=====FUNCTIONS=====");
    functions::run();
    println!("=====POINTERS / REFS=====");
    pointer_ref::run();
    println!("=====STRUCTS=====");
    structs::run();
    println!("=====ENUMS=====");
    enums::run();
    println!("=====CLI=====");
    cli::run();
    println!("=====TRAITS=====");
    traits::run();
    println!("===WRAP UNWRAP===");
    wrap_unwrap::run();
    println!("===ALIENT TYPES===");
    alient_types::run();
}
